config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :deliveries
  devise_for :users
  root to: "home#index"

  get 'home/index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/delivery.rb
class Delivery < ApplicationRecord
  has_many :orders, dependent: :destroy
  belongs_to :store

  validates :start_at, :close_at, :created_by, :store, presence: true

  delegate :name, to: :store, prefix: true

  class << self
    def active
      where("start_at < now() and close_at > now()").first
    end

    def next
      where("start_at >= now()").first
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items, dependent: :destroy
  accepts_nested_attributes_for :order_items, reject_if: :all_blank, allow_destroy: true

  belongs_to :delivery
  belongs_to :user

  has_one :store, through: :delivery

  enum preferred_payment_menthod: [:card, :cash]

  validates :delivery, :user, presence: true
  validate :at_least_one_item

  delegate :name, to: :store, prefix: true

  def total
    items = OrderItem.where(order_id: id).joins(:store_item)
      .select("sum(price * quantity) as total")
      .group(:order_id).to_a.last
    if items.present?
      items.total
    else
      0
    end
  end

  private

  def at_least_one_item
    if order_items.size < 1
      errors.add(:base, 'At least one item required to order')
    end
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :store_item

  validates :order, :store_item, :quantity, presence: true
  validates :quantity, numericality: { greater_than: 0 }

  delegate :label, to: :store_item
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :store_items
  has_many :deliveries

  validates :name, presence: true
end

app/models/store_item.rb
class StoreItem < ApplicationRecord
  has_many :order_items, dependent: :restrict_with_exception

  belongs_to :store

  validates :name, :price, :store, presence: true
  validates :price, numericality: { greater_than: 0 }

  def label
    "#{name} : #{'%.2f' % price} BYN"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :orders

  validates :email, format: { with: /.*@1pt.com/ }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def active_orders
    orders.where(delivery: Delivery.active)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def active_delivery
    @active_delivery ||= Delivery.active
  end
  helper_method :active_delivery
end

app/controllers/deliveries_controller.rb
class DeliveriesController < ApplicationController
  before_action :set_delivery, only: [:show, :edit, :update, :destroy]

  # GET /deliveries
  # GET /deliveries.json
  def index
    @deliveries = Delivery.all
  end

  # GET /deliveries/1
  # GET /deliveries/1.json
  def show
  end

  # GET /deliveries/new
  def new
    @delivery = Delivery.new
  end

  # GET /deliveries/1/edit
  def edit
  end

  # POST /deliveries
  # POST /deliveries.json
  def create
    @delivery = Delivery.new(delivery_params)

    respond_to do |format|
      if @delivery.save
        format.html { redirect_to @delivery, notice: 'Delivery was successfully created.' }
        format.json { render :show, status: :created, location: @delivery }
      else
        format.html { render :new }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deliveries/1
  # PATCH/PUT /deliveries/1.json
  def update
    respond_to do |format|
      if @delivery.update(delivery_params)
        format.html { redirect_to @delivery, notice: 'Delivery was successfully updated.' }
        format.json { render :show, status: :ok, location: @delivery }
      else
        format.html { render :edit }
        format.json { render json: @delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deliveries/1
  # DELETE /deliveries/1.json
  def destroy
    @delivery.destroy
    respond_to do |format|
      format.html { redirect_to deliveries_url, notice: 'Delivery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_delivery
      @delivery = Delivery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def delivery_params
      params.require(:delivery).permit(:store_id, :start_at, :close_at, :deliver_at, :discount, :created_by, :card_number)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @future_delivery = Delivery.next
    @orders = user_signed_in? ? current_user.active_orders.includes(order_items: :store_item) : Order.none
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :validate_delivery, only: [:new, :create]
  before_action :authenticate_user!

  def index
    @orders = Order.all
  end

  def show
  end

  def new
    @order = Order.new(user: current_user, delivery: active_delivery)
    @order.order_items.build if @order.order_items.empty?
  end

  def edit
  end

  def create
    @order = Order.new(order_params.merge(user: current_user, delivery: active_delivery))

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private
  def set_order
    @order = Order.find(params[:id])
  end

  def validate_delivery
    redirect_to(root_path, alert: 'No active delivery') && return unless active_delivery
  end

  def order_params
    params.require(:order).permit(
      :delivery_id, :user_id, :preferred_payment_method,
      order_items_attributes: [:store_item_id, :quantity, :_destroy, :id]
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/deliveries/_form.html.erb
<%= simple_form_for(@delivery) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :store %>
    <%= f.input :start_at %>
    <%= f.input :close_at %>
    <%= f.input :deliver_at %>
    <%= f.input :discount %>
    <%= f.input :created_by %>
    <%= f.input :card_number %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/deliveries/edit.html.erb
<h1>Editing Delivery</h1>

<%= render 'form', delivery: @delivery %>

<%= link_to 'Show', @delivery %> |
<%= link_to 'Back', deliveries_path %>

app/views/deliveries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Deliveries</h1>

<table>
  <thead>
    <tr>
      <th>Store</th>
      <th>Start at</th>
      <th>Close at</th>
      <th>Deliver at</th>
      <th>Discount</th>
      <th>Created by</th>
      <th>Card number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deliveries.each do |delivery| %>
      <tr>
        <td><%= delivery.store_name %></td>
        <td><%= delivery.start_at %></td>
        <td><%= delivery.close_at %></td>
        <td><%= delivery.deliver_at %></td>
        <td><%= delivery.discount %></td>
        <td><%= delivery.created_by %></td>
        <td><%= delivery.card_number %></td>
        <td><%= link_to 'Show', delivery %></td>
        <td><%= link_to 'Edit', edit_delivery_path(delivery) %></td>
        <td><%= link_to 'Destroy', delivery, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Delivery', new_delivery_path %>

app/views/deliveries/new.html.erb
<h1>New Delivery</h1>

<%= render 'form', delivery: @delivery %>

<%= link_to 'Back', deliveries_path %>

app/views/deliveries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Store:</strong>
  <%= @delivery.store %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @delivery.start_at %>
</p>

<p>
  <strong>Close at:</strong>
  <%= @delivery.close_at %>
</p>

<p>
  <strong>Deliver at:</strong>
  <%= @delivery.deliver_at %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @delivery.discount %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @delivery.created_by %>
</p>

<p>
  <strong>Card number:</strong>
  <%= @delivery.card_number %>
</p>

<%= link_to 'Edit', edit_delivery_path(@delivery) %> |
<%= link_to 'Back', deliveries_path %>

app/views/home/index.html.erb
<h1>Hello</h1>
<p>Get your shawarma here</p>


<% if active_delivery %>
  <p>Shawarma ordering will be closed at <%= active_delivery.close_at %></p>
  <% if @orders.present? %>
    <p>Your orders for this delivery</p>
    <% @orders.each do |order| %>
      <% order.order_items.each do |item| %>
        <p class="alert-info"><%= item.label %></p>
        <p class="alert-danger"><b>Quantity: </b><%= item.quantity %></p>
      <% end %>
    <% end %>

    <p class="align-bottom">Total: <%= @orders.map(&:total).sum %></p>
  <% end %>
<% elsif @future_delivery %>
  <p>Shawarma ordering will start at <%= @future_delivery.start_at %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shawarma</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-expand-lg navbar-light bg-light">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <% if user_signed_in? && current_user.admin? %>
          <li class="nav-item">
            <%= link_to('Deliveries', deliveries_path, class: 'nav-link') %>
          </li>
        <% end %>
        <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to('Orders', orders_path, class: 'nav-link') %>
            </li>
        <% end %>
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: 'nav-link') %>
          <% else %>
            <%= link_to('Login', new_user_session_path, class: 'nav-link')  %>
          <% end %>
        </li>
      </ul>
    </header>
    <div class="container-fluid">
      <div class="row justify-content-md-center">
        <div class="col">
          <p class="notice"><%= notice %></p>
          <div class="alert alert-primary" role="alert">
            <%= alert %>
          </div>

          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= simple_form_for(@order) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :preferred_payment_method, collection: Order.preferred_payment_menthods, default: Order.preferred_payment_menthods.first %>
    <%= f.simple_fields_for(:order_items) do |items_form| %>
      <%= render 'order_item_fields', f: items_form %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Давай ещё', f, :order_items, class: 'btn btn-success' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/orders/_order_item_fields.html.erb
<div class="row nested-fields">
  <div class="col-6">
    <%= f.association :store_item, label_method: :label, label: 'Хавка' %>
  </div>
  <div class="col-4">
    <%= f.input :quantity, label: 'Сколько штук?' %>
  </div>
  <div class="col-2">
    <%= link_to_remove_association 'Не хочу это', f, class: 'btn btn-danger' %>
  </div>
</div>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Delivery</th>
      <th>Preferred payment method</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.store_name %></td>
        <td><%= order.preferred_payment_method %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Delivery:</strong>
  <%= @order.store_name %>
</p>

<p>
  <strong>Preferred payment method:</strong>
  <%= @order.preferred_payment_method %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>